### PR TITLE
Feature/resources view

### PR DESCRIPTION
**Pull request by arbulu89**
Implementation of a new page to show some resources that are useful for the project.
Initially, this content was coming in the wrapup view, but as the user won't go back there again, I just moved somewhere else.

The text are configurable through the `en.yml` files

- Show SSH commands to connect to the machines (they are created based in the created machines, it is dynamic)
- Show how to destroy and automate the project

image
image
image
video

### CODE REVIEW

**Review by stefanotorresi — COMMENTED** [review]
Hey @arbulu89 I'm not sure we actually need the collapsable here.
Have you tried normal headings and letting the user read the entire page by just scrolling?
@cyntss what do you think about this?

**Comment by arbulu89** [comment]
> Hey @arbulu89 I'm not sure we actually need the collapsable here.
> Have you tried normal headings and letting the user read the entire page by just scrolling?
> @cyntss what do you think about this?

This would be the result:
resources_expanded

**Comment by stefanotorresi** [comment]
Personally, I like it more, what do you think?

**Comment by arbulu89** [comment]
> Personally, I like it more, what do you think?

Yes, it might be better, as the content is not that large, so maybe we don't need to have the collapsables. The text is quite easy to identify and split visually.

**Comment by MalloZup** [comment]
I prefer the 1st UX seems less information. But I would just hear what UX team says on it

**Review by MalloZup — COMMENTED** [review]
my personal pov is better the initial UX on this , but I'm ok with whatever UX says is better

**Comment by stefanotorresi** [comment]
@arbulu89 please do as it suits you best :)

**Comment by arbulu89** [comment]
Merged with the open text layout

**Pull request merged**
