### PR TITLE
Update printed plan headers

### PR DESCRIPTION
**Pull request by arbulu89**
Update printed plan headers to remove the icons and use other styles.
I don't honestly know what to say... I kind of prefer the icons. Opinions?
**In draft stage just to get feedback. I might need to do some cleanup of not used methods if we agree to proceed**

New:
plan-new

Old:
plan-old

### CODE REVIEW

**Comment by stefanotorresi** [comment]
heh, I kinda preferred the icons too, but I'm biased :stuck_out_tongue:

**Comment by arbulu89** [comment]
@stefanotorresi @MalloZup The PR is ready for reviewing.
After talking with our UX colleagues, we have agreed that removing the icons is the way to go, as they look like as actions, rather than informative elements

**Review by MalloZup — APPROVED** [review]
thx. I find the version without icons more minimalist and simple :sunflower:

**Review by stefanotorresi — APPROVED** [review]
yup! good to merge.

**Pull request merged**
