### PR TITLE
Feature/storage account check

### PR DESCRIPTION
**Pull request by arbulu89**
Include an Azure storage account check. This checks the storage account with the HANA software. Otherwise, errors might happen during the deployment if invalid data is set.

**This check only looks for a correct storage account file share. If it exists or not and if the storage account key is correct. It doesn't check if the files are HANA software**

If an error occurs, it is shown in the plan page, to follow with the same mechanism used by terraform plan failure.

Find the information about how the Azure rest api works in:
https://docs.microsoft.com/en-us/rest/api/storageservices/get-file-metadata
https://docs.microsoft.com/en-us/rest/api/storageservices/get-directory-metadata

Besides that, I have structured the code to make easy to add additional checks (like the ssh public key sanity check that will come after this PR).

**PD: Even though I have written many UT, there some few points that I was not able to cover. They are not that important, so I won't invest more time to cover one line as It is getting my a lot of time...**

Here some pics:
Invalid storage account used:
image
Invalid key (mostly the last 2 `==` not added). For some reason the API rest works without them... but afterwards the CIFS mounting fails...
image
Invalid key:
image
Invalid resource (hana software path)
image

### CODE REVIEW

**Review by stefanotorresi — COMMENTED** [review]
Overall it's a very welcomed change, as I told you earlier, but I'm not super keen about the UX, with the flash message above the page body and other detailed error messages within the body itself. I find it a little confusing.
Since we cannot have inline error message within the form as one would normally do, we need to at least optimize the "review and confirm" page presentation for such cases.

Any ideas?

Maybe @cyntss could help us here?

**Comment by arbulu89** [comment]
> Overall it's a very welcomed change, as I told you earlier, but I'm not super keen about the UX, with the flash message above the page body and other detailed error messages within the body itself. I find it a little confusing.
> Since we cannot have inline error message within the form as one would normally do, we need to at least optimize the "review and confirm" page presentation for such cases.
> 
> Any ideas?
> 
> Maybe @cyntss could help us here?

Keep in mind that the error messages are not only coming from this check. They might come from the `terraform plan` failure itself, and not all of the message content is something we can control by now (we just bypass the error message).
In general, the idea is just to explain the user what they did wrong to go back to the variables pages and fix.

As commented by @stefanotorresi , we cannot change this to happen in the variables form itself due some technical limitations that would require to do a major change in the code.

**Comment by stefanotorresi** [comment]
Yeah, I didn't intend to suggest any major changes in how the errors are handled in the back-end, rather just cosmetic changes that might improve the situation.
For example:
The flash message could warn the users with the text "One or multiple errors have occurred while preparing the plan" or "One or multiple errors have occurred while checking user input" and then, in both cases, instruct them with "Please check below for details".
Then properly color-code the single errors in the body using bootstrap classes like `.text-danger` or `.text-warning`, and present them in a bullet list or some other structure.

Can we do this? What do you think?

**Comment by arbulu89** [comment]
> Yeah, I didn't intend to suggest any major changes in how the errors are handled in the back-end, rather just cosmetic changes that might improve the situation.
> For example:
> The flash message could warn the users with the text "One or multiple errors have occurred while preparing the plan" or "One or multiple errors have occurred while checking user input" and then, in both cases, instruct them with "Please check below for details".
> Then properly color-code the single errors in the body using bootstrap classes like `.text-danger` or `.text-warning`, and present them in a bullet list or some other structure.
> 
> Can we do this? What do you think?

- It can be done, but it is not that easy for all the scenarios. The flash message gets the text from terraform output so times, so this would require changes there too.
- Besides that, the error raising system is `First found first raised`, so if something goes wrong it raises it without checking more things. If we want to change this, we need more changes too. The issue is that, this would require most probably `terraform` error messages parsing and formatting, as right now, they are just totally redirected to the app.
- For the reason explained before, there is not a list of errors, there is always a unique error by now. We can stylize the paragraph of course

**Comment by stefanotorresi** [comment]
Okay, forget about showing all the errors then, let's focus on just presenting what we already have a little better. I don't think we need to change the back-end any further, I just long for a better presentation of what we currently have, i.e. making more apparent that what is shown in the body is an error, and it's a follow-up of the flash message.

**Comment by arbulu89** [comment]
@stefanotorresi As this feature is not a `hard-requirement`, I will give a shot and try to redo the feature to work in the `variables` stage. As the `variables` object is not a standard `ActiveRecord` I will need to some uncommon implementations. 
Let's see.
Otherwise, styling the plan paragraph just changes the text color mostly, so it would be pretty much the same

**Comment by arbulu89** [comment]
@stefanotorresi I'm merging this PR as we already commented this topic with the rest of the team offline. Agree?

**Comment by stefanotorresi** [comment]
All right!

**Pull request merged**
