### PR TITLE
Implement the sidebar and top menu

### PR DESCRIPTION
**Pull request by arbulu89**
Implement the sidebar and top menu implementation.

Now, when the deployment is finished, the top menu is enabled, where the `Monitoring` and `Tuning` are available.

The sidebar is composed based in the data on the `customization.json` file (explained in the README file).

**TODO**:
Out of scope of this PR:
- The default page if you get `/` continues being the welcome page. This is wrong. When the deployment is finished, some of the entries in the console should be the default pages.
- Deployment pages are still available. We should block them when the deployment is finished.

**INFO**. To test the value `ha_sap_deployment_repo` must be uncommented, as the saptune exporter is not released officially yet

### CODE REVIEW

**Comment by arbulu89** [comment]
Some images:
image
image
ntent.com/36370954/100365827-458e0280-3000-11eb-9c52-c93905a32afd.png)
image

**Comment by arbulu89** [comment]
@stefanotorresi @MalloZup Can you have a look on this please?

**Comment by stefanotorresi** [comment]
> **INFO**. To test the value `ha_sap_deployment_repo` must be uncommented, as the saptune exporter is not released officially yet

I didn't quite understand this. Could you elaborate?

**Comment by arbulu89** [comment]
> > **INFO**. To test the value `ha_sap_deployment_repo` must be uncommented, as the saptune exporter is not released officially yet
> 
> I didn't quite understand this. Could you elaborate?

The deployment doesn't work unless we enable our development obs repository since we added the usage of the `saptune_exporter`. I just didn't want to make the change permanent, as the package should come somehow from official channels.

Maybe the phrase is not correctly formatted too. It should be ```**INFO**. To us the project by now the value `ha_sap_deployment_repo` must be uncommented, as the saptune exporter is not released officially yet```

**Comment by stefanotorresi** [comment]
Hmm, why not just leave the line then? We are still developing and testing. What's the point of commenting that value?

**Comment by arbulu89** [comment]
> Hmm, why not just leave the line then? We are still developing and testing. What's the point of commenting that value?

Ok, that's fair. As I just removed that in the past I didn't want to introduce it again, as it can introduce `non-production` packages without us noticing.
But yes, let's leave it as it is
**Edit** I mean, leave it uncommented hehe

**Comment by stefanotorresi** [comment]
Well the problem needs to be fixed elsewhere, namely we need to ensure that we have all the packages we need on PackageHub. Once we do this, we'll be able to remove the devel repo. :)

**Comment by arbulu89** [comment]
@stefanotorresi Change on `ha_sap_deployments_repo` implemented https://github.com/SUSE/blue-horizon/pull/13/commits/206836a8eb81bf053513a1d74a8de410e1d12e42

**Review by stefanotorresi — APPROVED** [review]
lgtm!

**Pull request merged**
