### PR TITLE
Add home page view

### PR DESCRIPTION
**Pull request by arbulu89**
Add home page view. I have added this view for the next reasons:
- To have a main view where we can put some information
- Have a default page to go if we try to use an invalid url. This becomes important if we try to go back to any of the deployment views. As those won't work anymore, we need to have a page to fallback.
- As we have the console now, we don't really need to limit the page usage to one option. So this logic will only apply to the deployment part now.

Pending to do: 
- Change `wrapup` view by home `view`
- `Finish` button is still enabled if the deployment fails, what wouldn't make sense, as it would redirect the user to the welcome page without being able to rollback

With this current implementation the `Finished` entry goes away from the deployment sidebar. And the top menu is changed to have this information. So when we click `Finish` in the deploy page, the page is redirected to the new `home` view.

FYI: @cyntss, does this make sense from UX perspective?

Some shots (**The text in the home page can change**):
image

image

### CODE REVIEW

**Comment by arbulu89** [comment]
@stefanotorresi @MalloZup @diegoakechi Any thoughts on this?

**Review by stefanotorresi — COMMENTED** [review]
I'm afraid I don't quite understand what you're proposing here.

You say this is pending the substitution of the `wrapup` page with this new `home` one.
Why is that? Wouldn't it be better if we did this all in one PR? Otherwise this will look confusing at first.
The last page is now the first one? So what happens after the deploy phase now?
Also, the current copywriting of the wrapup page doesn't really make sense in a homepage.

Furthermore:

> * Have a default page to go if we try to use an invalid url. This becomes important if we try to go back to any of the deployment views. As those won't work anymore, we need to have a page to fallback.

I think this problem should be resolved in a separate PR and should be detached from the homepage use case.
If something is not found, redirection to a default page is actually not that great as UX (because the user ends up being somewhere unexpected), so I would take the chance to improve this and cover this case explicitly with a dedicated page saying "you tried to reach a page that is no longer available, because reasons", or something like that.

**Comment by arbulu89** [comment]
> I'm afraid I don't quite understand what you're proposing here.
> 
> You say this is pending the substitution of the `wrapup` page with this new `home` one.
> Why is that? Wouldn't it be better if we did this all in one PR? Otherwise this will look confusing at first.
> The last page is now the first one? So what happens after the deploy phase now?
> Also, the current copywriting of the wrapup page doesn't really make sense in a homepage.
> 
Here, I just meant that to have more meaningful request, the `wrapup` controller would be renamed to `home`, but I didn't do it yet, as I wanted to get feedback. It would go in this PR, not separated.

> Furthermore:
> 
> > * Have a default page to go if we try to use an invalid url. This becomes important if we try to go back to any of the deployment views. As those won't work anymore, we need to have a page to fallback.
> 
> I think this problem should be resolved in a separate PR and should be detached from the homepage use case.
> If something is not found, redirection to a default page is actually not that great as UX (because the user ends up being somewhere unexpected), so I would take the chance to improve this and cover this case explicitly with a dedicated page saying "you tried to reach a page that is no longer available, because reasons", or something like that.

The major motivation of this is just to have a fallback place and avoid the usage of deployment stages after having the deployment finished.

If we don't have any kind of `home` page, where we should redirect the calls to the deployment page? The `home` page is just a common place where the redirect goes. It just gets the same content of the `wrapup` page.

So, just to summarize:
We have a problem, the deployment page views are accesible after the deployment, which might create issues. Run the deployment again for example. So, we need a way to do this.
@stefanotorresi What would you suggest here? Creating a new page only for that takes the same effort as this current change. We can always print the error message in a flash error message at the top of the page, as we do during the deployment

**Comment by stefanotorresi** [comment]
Still confused. 😬 

> Here, I just meant that to have more meaningful request

What do you mean by "more meaningful request"?

I'm still not clear if the `home` would still be the post-deployment page (that currently being `wrapup`), or a generic `home` that is opened when you first open the web app.

> @stefanotorresi What would you suggest here? Creating a new page only for that takes the same effort as this current change. We can always print the error message in a flash error message at the top of the page, as we do during the deployment

So what's the main problem you're trying to solve here? Do you want to present an introductory message to the user when they first open the blue horizon app, or do you want a fall back for when they are done with the deployment? It seems to me that we are conflating these two, while they are actually different in purpose, even if the solution appears to be the same: a dedicated static view.
I don't like the flash message because it's session based, IMHO these only make sense in the context of a request returning to the same page (i.e. input forms).

As trivial as it might seem, I would suggest to not mix the messages "welcome to this thing" and "uh, oh, you weren't supposed to get back here!", because these are very different. If it's trivial, I'd say a dedicated page is the way to go.

**Comment by arbulu89** [comment]
> Still confused. grimacing
> 
> > Here, I just meant that to have more meaningful request
> 
> What do you mean by "more meaningful request"?
> 
Change `/wrapup` to `/home`.

> I'm still not clear if the `home` would still be the post-deployment page (that currently being `wrapup`), or a generic `home` that is opened when you first open the web app.
> 
The `home` page would be available only after the deployment. The current `wrapup` page has the risk that offers the deployment sidebar options.

> > @stefanotorresi What would you suggest here? Creating a new page only for that takes the same effort as this current change. We can always print the error message in a flash error message at the top of the page, as we do during the deployment
> 
> So what's the main problem you're trying to solve here? Do you want to present an introductory message to the user when they first open the blue horizon app, or do you want a fall back for when they are done with the deployment? It seems to me that we are conflating these two, while they are actually different in purpose, even if the solution appears to be the same: a dedicated static view.

As commented, I want to solve the problem for when the user tries to go to some deployment view once the deployment is done. We don't want this, as it's risky.
The `home` page is just a page to redirect yes. And as most of the apps has some kind of `home` page, where you can put some initial content, I just took advantage of this.

> I don't like the flash message because it's session based, IMHO these only make sense in the context of a request returning to the same page (i.e. input forms).
Well, this is how the app currently works during the deployment. It's not only for forms. What if the user just puts on the browser the `deploy` url? What should we do? Now, it redirects this to the `welcome` page with a flash error box saying that this step is not allowed.
> 
> As trivial as it might seem, I would suggest to not mix the messages "welcome to this thing" and "uh, oh, you weren't supposed to get back here!", because these are very different. If it's trivial, I'd say a dedicated page is the way to go.

Finally, the reason why I added the home page is to have a place to redirect when a request without any parameter comes as well (`http://localsthost:3000` as example). Now, the page redirects this to the `welcome` page, what is troubling again. What should we do with this?

**Comment by stefanotorresi** [comment]
Okay, so I think I understand now! Thanks for the patience... 😄 

I now reckon this is mostly just a naming issue.

Here is my opinion:

No, I wouldn't rename `wrapup` to `home` because `home` should be the same as the bare URL (i.e. `http://localsthost:3000`). If that is currently called `welcome`, it means we should actually rename `welcome` to `home`.

If you want something else other than `wrapup` to present the deployed console, then I would go with `console`, and we can redirect invalid requests to this one.

If flash messages are already in place, then I wouldn't bother implementing something better, even if I personally don't quite like the idea of redirecting on error (I would rather show a static error page with no flashes nor redirects, with a CTA to let the user decide what to do nex, but I understand this would require changing the current workflow a too much).

Clear enough?

**Comment by arbulu89** [comment]
> 
> Clear enough?

Yes. But I still think that I need more validation (and ideas to implement a better home page, this one doesn't look right). This feature introduces a quite big change in the UX flow, and I'm not even convinced with the implementation totally.
I prefer to hold it back right now

**Comment by arbulu89** [comment]
@stefanotorresi Changes finished.
The changes since we discussed are:
- I have changed `wrapup` controller by `home` controller
- Add new UT
- Polish some small code changes after adjusting the UT

**Review by stefanotorresi — CHANGES_REQUESTED** [review]
@arbulu89 The idea behind the change is fine, what is left for me is a naming issue: I'm still not fond of renaming `wrapup` to `home`, and I think we should use something else.

For me, `home` should be the first page that is opened when the app is launched, and it should correspond to the bare url (e.g. `http://localhost:3000`).
Since that is currently the `welcome` route, what I proposed above was to rename `welcome` to `home`, and rename `wrapup` to something else. I think `console` might be a good choice, but feel free to use something else.

I don't think that `home` is semantically correct for this route, since that is _not_ the homepage of the application, not until the deployment is done.

**Comment by stefanotorresi** [comment]
To further clarify, I would be okay with this route being labelled as "Home" in the UI navigation, because I realise that the navigation changes once the deployment is done, but my point is that the route itself doesn't correspond to the root of the entire app.

**Comment by arbulu89** [comment]
> @arbulu89 The idea behind the change is fine, what is left for me is a naming issue: I'm still not fond of renaming `wrapup` to `home`, and I think we should use something else.
> 
> For me, `home` should be the first page that is opened when the app is launched, and it should correspond to the bare url (e.g. `http://localhost:3000`).
> Since that is currently the `welcome` route, what I proposed above was to rename `welcome` to `home`, and rename `wrapup` to something else. I think `console` might be a good choice, but feel free to use something else.
> 
> I don't think that `home` is semantically correct for this route, since that is _not_ the homepage of the application, not until the deployment is done.

I don't really agree. 
For the strange nature of the project, we find an initial page that it only serves as initial point. After that it won't be used anymore.
When any user is using this project, I expect that the new `home` page will be the most used one. `welcome` page is not even reachable. We need to see the project as a `console` , and where the user will spend more time on.
Do we want to set this as `home`?

And about `home should be the first page` and `it should correspond to the bare url`. If do so we will find ourselves redirecting all the times the requests from bar url to welcome, to be redirected again to the new `.home`.
In my opinion, and again, due the strange nature of this project, the new `welcome` and `home` make more sense

**Comment by arbulu89** [comment]
> To further clarify, I would be okay with this route being labelled as "Home" in the UI navigation, because I realise that the navigation changes once the deployment is done, but my point is that the route itself doesn't correspond to the root of the entire app.

It does. It corresponds when the console is deployed. After the deployment the root url and `home` are the same (the root url is redirected to `home` at least)

**Review by stefanotorresi — APPROVED** [review]
All right! I see you feel quite strongly about this, so I won't stall it any further. ;)

**Pull request merged**
