### PR TITLE
Feature/deployment

### PR DESCRIPTION
**Pull request by arbulu89**
Implement and add required new files to enable the deployment on azure:

- Add required new gems (uglifier, execjs)
- Fix issue with sqlite usage
- Add deployment files
  - Nginx configuration. This configuration enables basic authentication, usage of files in the public folder and the webpage is redirected to port 80
  - Systemd file
  - Update spec file to add them

The spec file has been updated to offer 2 packages. The original `blue-horizon-for-sap` with the application, and `blue-horizion-for-sap-deployment` that includes the files required just in the deployment (that requires `blue-horizon-for-sap` too).

This way, we can install any of them (the deployment will be installed in our image to get everything)

### CODE REVIEW

**Review by stefanotorresi — APPROVED** [review]
lgtm!

**Review by stefanotorresi — CHANGES_REQUESTED** [review]
Actually, on second thought, I'm not sure we need a sub-package at all. After all, all we need the package for is exactly the deployment, so I guess we could always include the nginx config and dependency? I think that would simplify things a little.
What's the use case for having a separate package?

**Comment by arbulu89** [comment]
> Actually, on second thought, I'm not sure we need a sub-package at all. After all, all we need the package for is exactly the deployment, so I guess we could always include the nginx config and dependency? I think that would simplify things a little.
> What's the use case for having a separate package?

I see some few advantages, and the added complexity is not that important:
- With 2 packages we follow the same structure than the original blue-horizon. 1 package for the app, 1 for the config. I find it easier to visualize the purpose of each of the groups of files
- We could install the package in other environments out of the cloud if we want to do so (to test locally, or in a container for example, we don't need nginx nor systemd for that)

Anyway, we can just have a unique package

**Comment by stefanotorresi** [comment]
> * With 2 packages we follow the same structure than the original blue-horizon. 1 package for the app, 1 for the config. I find it easier to visualize the purpose of each of the groups of files
> * We could install the package in other environments out of the cloud if we want to do so (to test locally, or in a container for example, we don't need nginx nor systemd for that)

Fair enough, then!

**Review by stefanotorresi — APPROVED** [review]

**Pull request merged**
